<h2>Finalizar pre-adopción</h2>

<p>
    <strong>Hijo:</strong>
    <?= h($hijo->nombre . ' ' . $hijo->apellidos) ?>
</p>

<p>
    <strong>Progenitor:</strong>
    <?= h($progenitor->nombre . ' ' . $progenitor->apellidos) ?>
</p>

<p>
    <strong>Inicio de la pre-adopción:</strong>
    <?= h($filiacion->fecha_inicio) ?>
</p>

<?= Form::open() ?>

<div class="form-group">
    <?= Form::label('fecha_fin', 'Fecha de finalización') ?>

    <?= Form::date(
        'fecha_fin',
        array(
            'min' => "$filiacion->fecha_inicio",
            'max' => date('Y-m-d'),
            'required' => 'required'
        ),
        "$filiacion->fecha_inicio"
    ) ?>
</div>

<div class="form-actions">
    <?= Form::submit(
        'Finalizar pre-adopción',
        array(
            'class' => 'btn btn-primary',
            'onclick' => 'return confirm("¿Está seguro de que desea finalizar esta pre-adopción?");'
        )
    ) ?>

    <?= Html::link(
        'personas/familia/' . $hijo->id,
        'Cancelar',
        array(
            'class' => 'btn btn-primary'
        )
    ) ?>
</div>

<?= Form::close() ?>
