<h1>Genealogía</h1>

<h2>Crear administrador inicial</h2>

<p>
    La aplicación no tiene ningún usuario creado.
    Debe crear el administrador inicial para comenzar.
</p>

<?= Form::open() ?>

<p>
    <?= Form::label(
        'nombre',
        'Nombre'
    ) ?>

    <?= Form::text(
        'nombre',
        ''
    ) ?>
</p>

<p>
    <?= Form::label(
        'username',
        'Usuario'
    ) ?>

    <?= Form::text(
        'username',
        ''
    ) ?>
</p>

<p>
    <?= Form::label(
        'password',
        'Contraseña'
    ) ?>

    <?= Form::password(
        'password',
        ''
    ) ?>
</p>

<p>
    <?= Form::label(
        'password_confirmacion',
        'Repetir contraseña'
    ) ?>

    <?= Form::password(
        'password_confirmacion',
        ''
    ) ?>
</p>

<p>
    <?= Form::submit('Crear administrador') ?>
</p>

<?= Form::close() ?>
