<h1>Genealogía</h1>

<h2>Iniciar sesión</h2>

<?= Form::open() ?>

<p>
    <?= Form::label(
        'username',
        'Usuario'
    ) ?>

    <?= Form::text(
        'username',
        ''
    ) ?>
</p>

<p>
    <?= Form::label(
        'password',
        'Contraseña'
    ) ?>

    <?= Form::password(
        'password',
        ''
    ) ?>
</p>

<p>
    <?= Form::submit('Entrar') ?>
</p>

<?= Form::close() ?>